
// Code generated by stanc v2.29.1
#include <stan/model/model_header.hpp>
namespace generate_multilevel_data2_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 26> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 17, column 3 to column 39)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 18, column 3 to column 28)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 19, column 3 to column 26)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 20, column 3 to column 33)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 22, column 7 to column 39)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 21, column 23 to line 23, column 4)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 21, column 3 to line 23, column 4)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 25, column 8 to column 42)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 26, column 8 to column 87)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 27, column 8 to column 101)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 24, column 18 to line 28, column 5)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 24, column 3 to line 28, column 5)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 2, column 3 to column 15)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 3, column 3 to column 9)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 7, column 3 to column 28)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 8, column 3 to column 24)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 9, column 3 to column 27)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 10, column 3 to column 30)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 11, column 3 to column 25)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 12, column 10 to column 17)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 12, column 3 to column 52)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 17, column 36 to column 37)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 18, column 19 to column 26)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 19, column 23 to column 24)",
 " (in '/Users/jerzybaranowski/GitHub/KAIR-ISZ/public_data/IoT/generate_multilevel_data2.stan', line 20, column 30 to column 31)"};




class generate_multilevel_data2_model final : public model_base_crtp<generate_multilevel_data2_model> {

 private:
  int N_batch;
  int N;
  double reset_intercept;
  double reset_slope;
  double shape;
  double failure_intercept;
  double failure_slope;
  Eigen::Matrix<double, -1, 1> theta__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> theta{nullptr, 0};
 
 public:
  ~generate_multilevel_data2_model() { }
  
  inline std::string model_name() const final { return "generate_multilevel_data2_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.1", "stancflags = "};
  }
  
  
  generate_multilevel_data2_model(stan::io::var_context& context__,
                                  unsigned int random_seed__ = 0,
                                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "generate_multilevel_data2_model_namespace::generate_multilevel_data2_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 13;
      context__.validate_dims("data initialization","N_batch","int",
           std::vector<size_t>{});
      N_batch = std::numeric_limits<int>::min();
      
      
      current_statement__ = 13;
      N_batch = context__.vals_i("N_batch")[(1 - 1)];
      current_statement__ = 14;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 14;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 15;
      reset_intercept = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 15;
      reset_intercept = 3;
      current_statement__ = 16;
      reset_slope = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 16;
      reset_slope = 1;
      current_statement__ = 17;
      shape = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 17;
      shape = 8;
      current_statement__ = 18;
      failure_intercept = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 18;
      failure_intercept = 0;
      current_statement__ = 19;
      failure_slope = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 19;
      failure_slope = 1;
      current_statement__ = 20;
      stan::math::validate_non_negative_index("theta", "N_batch", N_batch);
      current_statement__ = 21;
      theta__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N_batch,
          std::numeric_limits<double>::quiet_NaN());
      new (&theta) Eigen::Map<Eigen::Matrix<double, -1, 1>>(theta__.data(), N_batch);
        
      
      current_statement__ = 21;
      stan::model::assign(theta, stan::math::uniform_simplex(N_batch),
        "assigning variable theta");
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "shape", shape, 0);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("batch", "N", N);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("batch_coef", "N_batch",
                                              N_batch);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("resets", "N", N);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("failure_time", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 0U;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "generate_multilevel_data2_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "generate_multilevel_data2_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<int> batch =
         std::vector<int>(N, std::numeric_limits<int>::min());
      std::vector<double> batch_coef =
         std::vector<double>(N_batch, 
           std::numeric_limits<double>::quiet_NaN());
      std::vector<int> resets =
         std::vector<int>(N, std::numeric_limits<int>::min());
      std::vector<double> failure_time =
         std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      for (int k = 1; k <= N_batch; ++k) {
        current_statement__ = 5;
        stan::model::assign(batch_coef,
          stan::math::normal_rng(1, 1, base_rng__),
          "assigning variable batch_coef", stan::model::index_uni(k));
      }
      current_statement__ = 12;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 8;
        stan::model::assign(batch,
          stan::math::categorical_rng(theta, base_rng__),
          "assigning variable batch", stan::model::index_uni(n));
        current_statement__ = 9;
        stan::model::assign(resets,
          stan::math::poisson_rng(
            stan::math::exp(
              (reset_intercept +
                (reset_slope *
                  stan::model::rvalue(batch_coef, "batch_coef",
                    stan::model::index_uni(stan::model::rvalue(batch,
                                             "batch",
                                             stan::model::index_uni(n))))))),
            base_rng__),
          "assigning variable resets", stan::model::index_uni(n));
        current_statement__ = 10;
        stan::model::assign(failure_time,
          stan::math::gamma_rng(shape,
            stan::math::exp(
              (failure_intercept +
                (failure_slope *
                  stan::model::rvalue(batch_coef, "batch_coef",
                    stan::model::index_uni(stan::model::rvalue(batch,
                                             "batch",
                                             stan::model::index_uni(n))))))),
            base_rng__),
          "assigning variable failure_time", stan::model::index_uni(n));
      }
      current_statement__ = 1;
      stan::math::check_greater_or_equal(function__, "batch", batch, 0);
      current_statement__ = 1;
      stan::math::check_less_or_equal(function__, "batch", batch, N_batch);
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "resets", resets, 0);
      current_statement__ = 4;
      stan::math::check_greater_or_equal(function__, "failure_time",
                                            failure_time, 0);
      out__.write(batch);
      out__.write(batch_coef);
      out__.write(resets);
      out__.write(failure_time);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"batch", "batch_coef", "resets",
      "failure_time"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(N)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(N_batch)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "batch" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N_batch; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "batch_coef" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "resets" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "failure_time" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "batch" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N_batch; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "batch_coef" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "resets" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "failure_time" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"batch\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"batch_coef\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N_batch) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"resets\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"failure_time\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"batch\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"batch_coef\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N_batch) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"resets\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"int\"}},\"block\":\"generated_quantities\"},{\"name\":\"failure_time\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (((N + N_batch) + N) + N);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (((N + N_batch) + N) + N);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 0> names__{};
      const std::array<Eigen::Index, 0> constrain_param_sizes__{};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = generate_multilevel_data2_model_namespace::generate_multilevel_data2_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return generate_multilevel_data2_model_namespace::profiles__;
}

#endif


