
// Code generated by stanc v2.26.1
#include <stan/model/model_header.hpp>
namespace spline_fit_4_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 20, column 2 to column 18)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 21, column 2 to column 22)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 22, column 2 to column 11)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 23, column 2 to column 23)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 31, column 2 to column 17)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 32, column 2 to column 17)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 33, column 2 to column 15)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 34, column 2 to column 31)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 35, column 2 to column 18)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 36, column 2 to column 39)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 26, column 2 to column 29)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 27, column 2 to column 26)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 28, column 2 to column 35)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 2, column 2 to column 17)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 3, column 2 to column 17)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 4, column 2 to column 17)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 5, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 5, column 12 to column 13)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 5, column 2 to column 17)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 6, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 6, column 2 to column 14)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 9, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 9, column 12 to column 13)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 9, column 2 to column 21)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 10, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 10, column 12 to column 13)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 10, column 2 to column 21)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 11, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 11, column 12 to column 13)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 11, column 2 to column 29)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 12, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 12, column 2 to column 38)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 13, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 13, column 11 to column 12)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 13, column 2 to column 39)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 15, column 2 to column 37)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 16, column 2 to column 37)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 17, column 2 to column 33)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 20, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 31, column 9 to column 10)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 32, column 14 to column 15)",
                                                      " (in '/Users/jerzybaranowski/GitHub/isz/src/python/cables/spline_fit_4.stan', line 33, column 9 to column 10)"};



class spline_fit_4_model final : public model_base_crtp<spline_fit_4_model> {

 private:
  int N;
  int K;
  int L;
  Eigen::Matrix<double, -1, -1> x;
  Eigen::Matrix<double, -1, 1> y;
  Eigen::Matrix<double, -1, -1> Q_ast;
  Eigen::Matrix<double, -1, -1> R_ast;
  Eigen::Matrix<double, -1, -1> R_ast_inverse;
  Eigen::Matrix<double, -1, 1> ones_L;
  Eigen::Matrix<double, -1, -1> sub_X;
 
 public:
  ~spline_fit_4_model() { }
  
  inline std::string model_name() const final { return "spline_fit_4_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1", "stancflags = "};
  }
  
  
  spline_fit_4_model(stan::io::var_context& context__,
                     unsigned int random_seed__ = 0,
                     std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "spline_fit_4_model_namespace::spline_fit_4_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 14;
      current_statement__ = 14;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 15;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 15;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 15;
      current_statement__ = 15;
      check_greater_or_equal(function__, "K", K, 0);
      current_statement__ = 16;
      context__.validate_dims("data initialization","L","int",
          context__.to_vec());
      L = std::numeric_limits<int>::min();
      
      current_statement__ = 16;
      L = context__.vals_i("L")[(1 - 1)];
      current_statement__ = 16;
      current_statement__ = 16;
      check_greater_or_equal(function__, "L", L, 0);
      current_statement__ = 17;
      validate_non_negative_index("x", "N", N);
      current_statement__ = 18;
      validate_non_negative_index("x", "K", K);
      current_statement__ = 19;
      context__.validate_dims("data initialization","x","double",
          context__.to_vec(N, K));
      x = Eigen::Matrix<double, -1, -1>(N, K);
      stan::math::fill(x, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 19;
        assign(x_flat__, nil_index_list(), context__.vals_r("x"),
          "assigning variable x_flat__");
        current_statement__ = 19;
        pos__ = 1;
        current_statement__ = 19;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 19;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 19;
            assign(x,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              x_flat__[(pos__ - 1)], "assigning variable x");
            current_statement__ = 19;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 20;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 21;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(N));
      y = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(y, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 21;
        assign(y_flat__, nil_index_list(), context__.vals_r("y"),
          "assigning variable y_flat__");
        current_statement__ = 21;
        pos__ = 1;
        current_statement__ = 21;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 21;
          assign(y, cons_list(index_uni(sym1__), nil_index_list()),
            y_flat__[(pos__ - 1)], "assigning variable y");
          current_statement__ = 21;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 22;
      validate_non_negative_index("Q_ast", "N", N);
      current_statement__ = 23;
      validate_non_negative_index("Q_ast", "K", K);
      current_statement__ = 24;
      Q_ast = Eigen::Matrix<double, -1, -1>(N, K);
      stan::math::fill(Q_ast, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 25;
      validate_non_negative_index("R_ast", "K", K);
      current_statement__ = 26;
      validate_non_negative_index("R_ast", "K", K);
      current_statement__ = 27;
      R_ast = Eigen::Matrix<double, -1, -1>(K, K);
      stan::math::fill(R_ast, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 28;
      validate_non_negative_index("R_ast_inverse", "K", K);
      current_statement__ = 29;
      validate_non_negative_index("R_ast_inverse", "K", K);
      current_statement__ = 30;
      R_ast_inverse = Eigen::Matrix<double, -1, -1>(K, K);
      stan::math::fill(R_ast_inverse, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 31;
      validate_non_negative_index("ones_L", "L", L);
      current_statement__ = 32;
      ones_L = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(ones_L, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 32;
      assign(ones_L, nil_index_list(), rep_vector(1, L),
        "assigning variable ones_L");
      current_statement__ = 33;
      validate_non_negative_index("sub_X", "L", L);
      current_statement__ = 34;
      validate_non_negative_index("sub_X", "K", K);
      current_statement__ = 35;
      sub_X = Eigen::Matrix<double, -1, -1>(L, K);
      stan::math::fill(sub_X, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 35;
      assign(sub_X, nil_index_list(), block(x, 1, 1, L, K),
        "assigning variable sub_X");
      current_statement__ = 36;
      assign(Q_ast, nil_index_list(),
        multiply(qr_thin_Q(x), stan::math::sqrt((N - 1))),
        "assigning variable Q_ast");
      current_statement__ = 37;
      assign(R_ast, nil_index_list(),
        divide(qr_thin_R(x), stan::math::sqrt((N - 1))),
        "assigning variable R_ast");
      current_statement__ = 38;
      assign(R_ast_inverse, nil_index_list(), inverse(R_ast),
        "assigning variable R_ast_inverse");
      current_statement__ = 39;
      validate_non_negative_index("theta", "K", K);
      current_statement__ = 40;
      validate_non_negative_index("beta", "K", K);
      current_statement__ = 41;
      validate_non_negative_index("y_pred", "L", L);
      current_statement__ = 42;
      validate_non_negative_index("mu", "L", L);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += K;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "spline_fit_4_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> theta;
      theta = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(theta, DUMMY_VAR__);
      
      current_statement__ = 1;
      theta = in__.vector(K);
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 2;
      sigma = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        sigma = stan::math::lb_constrain(sigma, 0, lp__);
      } else {
        current_statement__ = 2;
        sigma = stan::math::lb_constrain(sigma, 0);
      }
      local_scalar_t__ mu0;
      mu0 = DUMMY_VAR__;
      
      current_statement__ = 3;
      mu0 = in__.scalar();
      local_scalar_t__ sigma0;
      sigma0 = DUMMY_VAR__;
      
      current_statement__ = 4;
      sigma0 = in__.scalar();
      current_statement__ = 4;
      if (jacobian__) {
        current_statement__ = 4;
        sigma0 = stan::math::lb_constrain(sigma0, 0, lp__);
      } else {
        current_statement__ = 4;
        sigma0 = stan::math::lb_constrain(sigma0, 0);
      }
      {
        current_statement__ = 11;
        lp_accum__.add(normal_lpdf<propto__>(theta, mu0, sigma0));
        current_statement__ = 12;
        lp_accum__.add(exponential_lpdf<propto__>(sigma, .1));
        current_statement__ = 13;
        lp_accum__.add(
          normal_lpdf<propto__>(y, multiply(Q_ast, theta), sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "spline_fit_4_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      theta = in__.vector(K);
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma = in__.scalar();
      current_statement__ = 2;
      sigma = stan::math::lb_constrain(sigma, 0);
      double mu0;
      mu0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu0 = in__.scalar();
      double sigma0;
      sigma0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      sigma0 = in__.scalar();
      current_statement__ = 4;
      sigma0 = stan::math::lb_constrain(sigma0, 0);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(theta[(sym1__ - 1)]);}
      vars__.emplace_back(sigma);
      vars__.emplace_back(mu0);
      vars__.emplace_back(sigma0);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<double> y_pred;
      y_pred = std::vector<double>(L, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(L);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 8;
      assign(beta, nil_index_list(), multiply(R_ast_inverse, theta),
        "assigning variable beta");
      current_statement__ = 9;
      assign(mu, nil_index_list(), multiply(sub_X, beta),
        "assigning variable mu");
      current_statement__ = 10;
      assign(y_pred, nil_index_list(),
        normal_rng(mu, multiply(ones_L, sigma), base_rng__),
        "assigning variable y_pred");
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        vars__.emplace_back(y_pred[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        vars__.emplace_back(mu[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 1;
        assign(theta_flat__, nil_index_list(), context__.vals_r("theta"),
          "assigning variable theta_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          assign(theta, cons_list(index_uni(sym1__), nil_index_list()),
            theta_flat__[(pos__ - 1)], "assigning variable theta");
          current_statement__ = 1;
          pos__ = (pos__ + 1);}
      }
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      double sigma_free__;
      sigma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma_free__ = stan::math::lb_free(sigma, 0);
      double mu0;
      mu0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu0 = context__.vals_r("mu0")[(1 - 1)];
      double sigma0;
      sigma0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      sigma0 = context__.vals_r("sigma0")[(1 - 1)];
      double sigma0_free__;
      sigma0_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      sigma0_free__ = stan::math::lb_free(sigma0, 0);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(theta[(sym1__ - 1)]);}
      vars__.emplace_back(sigma_free__);
      vars__.emplace_back(mu0);
      vars__.emplace_back(sigma0_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("theta");
    names__.emplace_back("sigma");
    names__.emplace_back("mu0");
    names__.emplace_back("sigma0");
    names__.emplace_back("beta");
    names__.emplace_back("y_pred");
    names__.emplace_back("mu");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(L)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(L)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "mu0");
    param_names__.emplace_back(std::string() + "sigma0");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_pred" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "mu0");
    param_names__.emplace_back(std::string() + "sigma0");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_pred" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= L; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"generated_quantities\"},{\"name\":\"y_pred\",\"type\":{\"name\":\"array\",\"length\":" << L << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"generated_quantities\"},{\"name\":\"y_pred\",\"type\":{\"name\":\"array\",\"length\":" << L << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << L << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}
using stan_model = spline_fit_4_model_namespace::spline_fit_4_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return spline_fit_4_model_namespace::profiles__;
}

#endif


